export const shipTypes = [
  { id: 20, name: "Wing in ground (WIG), all ships of this type" },
  { id: 21, name: "Wing in ground (WIG), Hazardous category A" },
  { id: 22, name: "Wing in ground (WIG), Hazardous category B" },
  { id: 23, name: "Wing in ground (WIG), Hazardous category C" },
  { id: 24, name: "Wing in ground (WIG), Hazardous category D" },
  { id: 25, name: "Wing in ground (WIG)" },
  { id: 26, name: "Wing in ground (WIG)" },
  { id: 27, name: "Wing in ground (WIG)" },
  { id: 28, name: "Wing in ground (WIG)" },
  { id: 29, name: "Wing in ground (WIG)" },
  { id: 30, name: "Fishing" },
  { id: 31, name: "Towing" },
  { id: 32, name: "Towing: length exceeds 200m or breadth exceeds 25m" },
  { id: 33, name: "Dredging or underwater ops" },
  { id: 34, name: "Diving ops" },
  { id: 35, name: "Military ops" },
  { id: 36, name: "Sailing" },
  { id: 37, name: "Pleasure Craft" },
  { id: 38, name: "Reserved" },
  { id: 39, name: "Reserved" },
  { id: 40, name: "High speed craft (HSC), all ships of this type" },
  { id: 41, name: "High speed craft (HSC), Hazardous category A" },
  { id: 42, name: "High speed craft (HSC), Hazardous category B" },
  { id: 43, name: "High speed craft (HSC), Hazardous category C" },
  { id: 44, name: "High speed craft (HSC), Hazardous category D" },
  { id: 45, name: "High speed craft (HSC)" },
  { id: 46, name: "High speed craft (HSC)" },
  { id: 47, name: "High speed craft (HSC)" },
  { id: 48, name: "High speed craft (HSC)" },
  { id: 49, name: "High speed craft (HSC)" },
  { id: 50, name: "Pilot Vessel" },
  { id: 51, name: "Search and Rescue vessel" },
  { id: 52, name: "Tug" },
  { id: 53, name: "Port Tender" },
  { id: 54, name: "Anti-pollution equipment" },
  { id: 55, name: "Law Enforcement" },
  { id: 56, name: "Spare - Local Vessel" },
  { id: 57, name: "Spare - Local Vessel" },
  { id: 58, name: "Medical Transport" },
  { id: 59, name: "Noncombatant ship according to RR Resolution No. 18" },
  { id: 60, name: "Passenger, all ships of this type" },
  { id: 61, name: "Passenger, Hazardous category A" },
  { id: 62, name: "Passenger, Hazardous category B" },
  { id: 63, name: "Passenger, Hazardous category C" },
  { id: 64, name: "Passenger, Hazardous category D" },
  { id: 65, name: "Passenger" },
  { id: 66, name: "Passenger" },
  { id: 67, name: "Passenger" },
  { id: 68, name: "Passenger" },
  { id: 69, name: "Passenger, No additional information" },
  { id: 70, name: "Cargo, all ships of this type" },
  { id: 71, name: "Cargo, Hazardous category A" },
  { id: 72, name: "Cargo, Hazardous category B" },
  { id: 73, name: "Cargo, Hazardous category C" },
  { id: 74, name: "Cargo, Hazardous category D" },
  { id: 75, name: "Cargo" },
  { id: 76, name: "Cargo" },
  { id: 77, name: "Cargo" },
  { id: 78, name: "Cargo" },
  { id: 79, name: "Cargo, No additional information" },
  { id: 80, name: "Tanker, all ships of this type" },
  { id: 81, name: "Tanker, Hazardous category A" },
  { id: 82, name: "Tanker, Hazardous category B" },
  { id: 83, name: "Tanker, Hazardous category C" },
  { id: 84, name: "Tanker, Hazardous category D" },
  { id: 85, name: "Tanker" },
  { id: 86, name: "Tanker" },
  { id: 87, name: "Tanker" },
  { id: 88, name: "Tanker" },
  { id: 89, name: "Tanker, No additional information" },
  { id: 90, name: "Other Type, all ships of this type" },
  { id: 91, name: "Other Type, Hazardous category A" },
  { id: 92, name: "Other Type, Hazardous category B" },
  { id: 93, name: "Other Type, Hazardous category C" },
  { id: 94, name: "Other Type, Hazardous category D" },
  { id: 95, name: "Other Type" },
  { id: 96, name: "Other Type" },
  { id: 97, name: "Other Type" },
  { id: 98, name: "Other Type" },
  { id: 99, name: "Other Type" },
];
